CREATE TABLE JOB_LOGS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    JOB_NAME VARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR2(50)
);

-- Grant permissions if necessary (usually handled by the default user in this image, but good practice)
-- In gvenzl/oracle-free, the user created via env vars has rights.
