using AsyncEnumerable_TEST_MVC.Interface;
using AsyncEnumerable_TEST_MVC.Services;
using DbService.Interface;
using DbService.Services;
using Oracle.ManagedDataAccess.Client;
using System.Data;

namespace AsyncEnumerable_TEST_MVC
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);

            // Add services to the container.
            builder.Services.AddControllersWithViews();
            builder.Services.AddScoped<IJobExecutionService, JobExecutionService>();
            builder.Services.AddTransient<IDbConnection>(sp => new OracleConnection(builder.Configuration.GetConnectionString("DefaultConnection")));
            builder.Services.AddTransient<ISqlRepository, SqlRepository>();
            var app = builder.Build();

            // Initialize Database
            using (var scope = app.Services.CreateScope())
            {
                var repo = scope.ServiceProvider.GetRequiredService<ISqlRepository>();
                try 
                {
                    // Simple check and create. In production, use migration tools.
                    repo.ExecuteAsync(@"
                        BEGIN
                            EXECUTE IMMEDIATE 'CREATE TABLE JOB_LOGS (
                                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                JOB_NAME VARCHAR2(100) NOT NULL,
                                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                STATUS VARCHAR2(50)
                            )';
                        EXCEPTION
                            WHEN OTHERS THEN
                                IF SQLCODE != -955 THEN -- ORA-00955: name is already used by an existing object
                                    RAISE;
                                END IF;
                        END;
                    ").Wait();
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"DB Init Error: {ex.Message}");
                }
            }

            // Configure the HTTP request pipeline.
            if (!app.Environment.IsDevelopment())
            {
                app.UseExceptionHandler("/Home/Error");
            }
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            app.MapControllerRoute(
                name: "default",
                pattern: "{controller=Home}/{action=Index}/{id?}");

            app.Run();
        }
    }
}
